name: learning-github-actions
run-name: ${{ github.actor }} is learning GitHub actions
on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.MONGO_URL }}
      DB_NAME: ${{ secrets.MONGO_DB_TEST }}
      DB_UNAME: ${{ secrets.MONGO_USER }}
      DB_PASSWD: ${{ secrets.MONGO_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest
  build-image:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t usebus-knee:$GITHUB_RUN_NUMBER .
      - name: Push image
        run: |
          docker tag usebus-knee:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_USERNAME }}/usebus-knee:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push usebus-knee:$GITHUB_RUN_NUMBER
